services:
  - type: worker
    name: whatsapp-gpt1.0
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
